### ISSUE TITLE
Migrate to using languageOptions.parserOptions for Eslint 9+

### ISSUE THREAD

**Issue by Goldziher** [jsx-eslint/eslint-plugin-jsx-a11y#1001]
This config uses a depracted key which causes the following issue:

Oops! Something went wrong! :(

ESLint: 9.8.0

A config object is using the "parserOptions" key, which is not supported in flat config system.

Flat config uses "languageOptions.parserOptions" to specify parser options.

Please see the following page for information on how to convert your config object into the correct format:
https://eslint.org/docs/latest/use/configure/migration-guide#configuring-language-options

If you're not using "parserOptions" directly (it may be coming from a plugin), please see the following:
https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config
 ELIFECYCLE  Command failed with exit code 2.

**Comment by ljharb** [comment]
We don't support flat config yet; see #993.
