### ISSUE TITLE
add fix options to rules where it makes sense

### ISSUE THREAD

**Issue by beefancohen** [jsx-eslint/eslint-plugin-jsx-a11y#138]
this is some low hanging fruit i think and would love some help either identifying rules that we think would be helpful with fixers or even creating them yourself!

**Comment by lb-** [comment]
See https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/951 - it appears that the autofix approach will not be supported by this package for the foreseeable future. Especially with the nuance of fixes that may be required, it makes sense to me also that autofix probably is not suitable for this package.

**Comment by ljharb** [comment]
Indeed, this is duplicated by #951.
