### ISSUE TITLE
Implement global settings

### ISSUE THREAD

**Issue by beefancohen** [jsx-eslint/eslint-plugin-jsx-a11y#174]
Discussed in #65. We can provide global settings API for users to specify mappings from low-level DOM elements to their associated wrapper component. This allows us to better apply the ruleset over a codebase. It can also have configuration options for `ARIA` convention for props (i.e. camel-casing like `ariaExpanded` or just `expanded`) that map to respective `ARIA` properties. Also contains a special property for `role` since that sometimes has conflicts (as seen in #166).

Can look something like this:

```json
{
	"settings": {
		"components": {
			"a": ["Link"],
			"abbr": [],
			"address": [],
			"area": [],
			"article": [],
			"aside": [],
			"audio": [],
			"b": [],
			"base": [],
			"bdi": [],
			"bdo": [],
			"big": [],
			"blockquote": [],
			"body": [],
			"br": [],
			"button": ["Button"],
			"canvas": [],
			"caption": [],
			"cite": [],
			"code": [],
			"col": [],
			"colgroup": [],
			"data": [],
			"datalist": [],
			"dd": [],
			"del": [],
			"details": [],
			"dfn": [],
			"dialog": [],
			"div": [],
			"dl": [],
			"dt": [],
			"em": [],
			"embed": [],
			"fieldset": [],
			"figcaption": [],
			"figure": [],
			"footer": ["Footer"],
			"form": [],
			"h1": [],
			"h2": [],
			"h3": [],
			"h4": [],
			"h5": [],
			"h6": [],
			"head": [],
			"header": ["Header"],
			"hgroup": [],
			"hr": [],
			"html": [],
			"i": [],
			"iframe": [],
			"img": ["Image"],
			"input": ["Input"],
			"ins": [],
			"kbd": [],
			"keygen": [],
			"label": ["Label"],
			"legend": [],
			"li": [],
			"link": [],
			"main": [],
			"map": [],
			"mark": [],
			"menu": [],
			"menuitem": [],
			"meta": [],
			"meter": [],
			"nav": [],
			"noscript": [],
			"object": [],
			"ol": [],
			"optgroup": [],
			"option": [],
			"output": [],
			"p": [],
			"param": [],
			"picture": [],
			"pre": [],
			"progress": [],
			"q": [],
			"rp": [],
			"rt": [],
			"ruby": [],
			"s": [],
			"samp": [],
			"script": [],
			"section": [],
			"select": [],
			"small": [],
			"source": [],
			"span": [],
			"strong": [],
			"style": [],
			"sub": [],
			"summary": [],
			"sup": [],
			"table": [],
			"tbody": [],
			"td": [],
			"textarea": [],
			"tfoot": [],
			"th": [],
			"thead": [],
			"time": [],
			"title": [],
			"tr": [],
			"track": [],
			"u": [],
			"ul": [],
			"var": [],
			"video": [],
			"wbr": []
		},
		"props": {
			"aria": "kebab",
			"role": "ariaRole"
		}
	}
}
```

**Comment by jessebeach** [comment]
hoohoo! Are you thinking that we could map custom components to html elements? like

```"button": ['AbstractButton', 'FancyButton', 'PopoverButton']```

**Comment by ljharb** [comment]
I’d still find value in this, fwiw.

**Comment by eps1lon** [comment]
@evcohen Was this abandoned? I see that you closed this with without referencing any commit, PR or other explanation.

**Comment by karltaylor** [comment]
This would really help when using jsx-a11y with `styled-components`. I hope this can be re-opened and looked at!

**Comment by jessebeach** [comment]
@karltaylor code examples would really help frame the enhancement. Could you post a few here?

**Comment by gabeodess** [comment]
Would love to see this working.  Currently having trouble with `jsx-a11y/label-has-for`:

```jsx
<label htmlFor={id}>
  <Checkbox id={id}/> Click Me!
</label>
```

Could be solved by:
```yaml
settings:
  components:
    input: ["Checkbox"]
```

**Comment by ljharb** [comment]
Considering this was closed without explanation, and I'd still like to see it happen, I'm going to reopen - @evcohen please feel free to re-close, but it'd be great to understand why :-)

**Comment by talentlessguy** [comment]
any progress on this?

**Comment by madalynrose** [comment]
Any updates on this? 

I really love this tool and recommend it everywhere I can. Establishing an API for mapping custom components and attributes to their equivalent semantic element would add a lot of power. I'd love a way to lint Gatsby's components (e.g.`<Link/>`, which expects a `to` attribute instead of an `href`). This is also especially useful for styled components, which are becoming increasingly popular with usage in frameworks like Gatsby. The discussion around explicit mapping in #466 touches on a specific use case for this feature and I hope it gets picked back up.

**Comment by heylookltsme** [comment]
Bump! Our company would love this for usage with styled components.  

It looks like [individual rules support](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/alt-text.md#rule-details) a mapping of the HTML element to custom components, but maintaining those maps on a per-rule basis is prohibitively tedious and difficult to scale/maintain. 

The solution proposed here - a global mapping of elements to components - would be fantastic. 🎉

**Comment by eps1lon** [comment]
>  I'd love a way to lint Gatsby's components (e.g.<Link/>, which expects a to attribute instead of an href).

This is a really good point. Any implementation should not only consider element mappings but also attribute mappings for custom props (per component) as well as disabling certain rules. Certain required aria attributes might be already set for custom components.

**Comment by pcorpet** [comment]
I've started a change in #844, if anyone wants to comment on the API I've chosen and my implementation. If you like it, I'll finish the remaining rules and add proper documentation.

**Comment by smithki** [comment]
Love to see that #844 is merged! I'm very much looking forward to seeing those changes land in a published release. Any thoughts on when that might happen? As of now, the README documentation [reflects support for global settings](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#usage), but that's not yet the case 😞

**Comment by ljharb** [comment]
@smithki on every repo on github, the readme on the default branch won't necessarily match the last published version, and you have to Just Know to change to a tag to see that version's docs.

There's no planned release time, but hopefully soon.

**Comment by ljharb** [comment]
v6.6.0 is released.

**Comment by ljharb** [comment]
I think #844 has resolved this, so I'm going to close.

If I'm wrong, what would be most helpful is filing a *new* issue that details any gaps, and why they're needed.
