### ISSUE TITLE
form onSubmit trips jsx-a11y/no-noninteractive-element-interactions rule

### ISSUE THREAD

**Issue by roubaobaozi** [jsx-eslint/eslint-plugin-jsx-a11y#323]
eg.
```jsx
<form onSubmit={this.handleSubmit.bind(this)} method="POST">
    <button type="submit">
        Save
    </button>
</form>
```

This rule makes sense for a `div` or `span` etc., but not in the above case.

**Comment by ljharb** [comment]
Indeed, forms should be able to have `onSubmit` (the issue that `.bind` in the render path is super slow would be handled by eslint-plugin-react :-) )

**Comment by Einere** [comment]
when this issue will resolve?

**Comment by ljharb** [comment]
@Einere when someone submits a PR for it.
