### ISSUE TITLE
onFocus and tabIndex="-1"

### ISSUE THREAD

**Issue by A** [jsx-eslint/eslint-plugin-jsx-a11y#521]
Hello and thank you for nice plugin. I have one question, and I'm am not an expert in ARIA stuff, but is it reasonable to ask for fallback mouse events with `onFocus` in case element has `tabIndex=-1`?

#### Example: 

```
<td
  tabIndex={-1}
  onMouseOver={this.toggleHover}
  onMouseLeave={this.toggleHover}
/>
// onMouseOver must be accompanied by onFocus for accessibility.eslint(jsx-a11y/mouse-events-have-key-events)
```

**Comment by gaurav5430** [comment]
I am interested in working on this if someone can guide me a bit on contributing to this repo and probably an overview of what fixes are required
