### ISSUE TITLE
The advice from jsx-a11y/accessible-emoji appears to lead to a degraded experience with assistive technologies

### ISSUE THREAD

**Issue by luke-john** [jsx-eslint/eslint-plugin-jsx-a11y#627]
From some testing on os x with VoiceOver, it seems the guidance provided in the rule jsx-a11y/accessible-emoji leads to a degraded experience with the label not being announced to the user.

I've setup a codepen which demonstrates this at the following link.

https://codepen.io/anon/pen/ymoBgb

The rule seemed to have been created based on the advice in a blog post from a few years ago now, so perhaps browsers and assistive technologies have advanced since then.

https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/136

**Comment by jessebeach** [comment]
@luke-john great suggestion. You're totally right. Emojis have evolved since this rule was created and it no longer makes sense. I'm going to deprecate this rule in the current version and we'll remove it in the next version.

**Comment by evcohen** [comment]
Thank you!!!!
