### ISSUE TITLE
jsx-a11y/control-has-associated-label not recognizing aria-hidden

### ISSUE THREAD

**Issue by heartistizio** [jsx-eslint/eslint-plugin-jsx-a11y#635]
Hey!

When I add `aria-hidden="true"` to the element I would expect this rule to ignore this particular control element. It seems not be the case.

Example

// rule config
```
'jsx-a11y/label-has-associated-control': [
  'error',
  {
    assert: 'either',
  }
],
```

`<input type="hidden" aria-hidden="true" />`

This fails.

Thanks!

**Comment by ljharb** [comment]
I would expect any `type=hidden` input to be exempted from this rule, aria-hidden or not.
