### ISSUE TITLE
jsx-a11y/no-interactive-element-to-noninteractive-role for canvas

### ISSUE THREAD

**Issue by markwoon** [jsx-eslint/eslint-plugin-jsx-a11y#648]
This rule currently does not allow `canvas` elements to be given the `img` role even though that's the recommendation (e.g. http://pauljadam.com/demos/canvas.html).

Would it be possible to add it as a standard exception the way `tr` is right now?

**Comment by SudharsanSukumar** [comment]
Can we get some traction on this?

**Comment by ljharb** [comment]
@SudharsanSukumar PRs are welcome
