### ISSUE TITLE
jsx-a11y/label-has-for is deprecated but still enabled in the strict rules

### ISSUE THREAD

**Issue by matijs** [jsx-eslint/eslint-plugin-jsx-a11y#664]
`jsx-a11y/label-has-for` is deprecated in favour of `label-has-associated-control` but is still part of the strict rules that the plugin provides.

I was wondering if it should be removed because in `strict` there are essentially two rules for the same issue.

I'm willing to submit a PR for this :)

**Comment by ljharb** [comment]
It’d be a breaking change imo, unless the new rule reports on 100% of the things the old one reports on, with that configuration.

**Comment by jessebeach** [comment]
We'll remove it in version 7.x.x
