### ISSUE TITLE
js-a11y/lang not recognizing script subtag

### ISSUE THREAD

**Issue by imtsuki** [jsx-eslint/eslint-plugin-jsx-a11y#669]
According to [the documentation for lang attribute on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang), a valid HTML lang attribute is composed of three parts: 

language-[script]-[region]

where the script subtag defines the writing system used for the language, and is always 4 characters long, with the first letter capitalized. This subtag is particularly useful as there are two different writing systems in Chinese: simplified (`Hans`) and traditional (`Hant`).

For example, I can have each of the following valid lang attributes:

- `zh-CN`
- `zh-Hant`
- `zh-Hans-CN`

But now the js-a11y/lang rule is rejecting the last two.

Reference:
- [lang - HTML: Hypertext Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang)

**Comment by imtsuki** [comment]
I did some investigation. There are actually three languages defined here:

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/7bcea2006f1d79b399e4aaec82e9cbbbe6ef8cc4/src/util/attributes/ISO.json#L262-L264

But the `indexOf('-')` here accidentally breaks the last two pairs, which causes the problem:

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/7bcea2006f1d79b399e4aaec82e9cbbbe6ef8cc4/src/rules/lang.js#L54-L56

**Comment by ljharb** [comment]
ah, maybe it should be `lastIndexOf`? or something more precise :-) want to make a PR?
