### ISSUE TITLE
jsx-a11y/aria-activedescendant-has-tabindex rule is incompatible with w3c wai-aria examples

### ISSUE THREAD

**Issue by KuSh** [jsx-eslint/eslint-plugin-jsx-a11y#673]
Hi,

I'm trying to implement wai-aria compatible components following w3c wai-aria-practices examples and the following rule causes me problems :
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/7bcea2006f1d79b399e4aaec82e9cbbbe6ef8cc4/src/rules/aria-activedescendant-has-tabindex.js#L46-L49

This rule doesn't validate w3c [following example](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html) as it uses negative tabIndex 

regards,
Nicolas

**Comment by jessebeach** [comment]
@KuSh ya, you're totally right. Thank you for bringing this to our attention!

<img width="764" alt="Collapsible_Dropdown_Listbox_Example___WAI-ARIA_Authoring_Practices_1_1" src="https://user-images.githubusercontent.com/345913/85212981-444c0180-b30d-11ea-86ba-cb33196539a4.png">

Let's remove the restriction on it being negative.
