### ISSUE TITLE
Bypass for no-redundant-roles for list with list-style set to none?

### ISSUE THREAD

**Issue by mikeriley131** [jsx-eslint/eslint-plugin-jsx-a11y#690]
According to a couple of articles posted over the last few years, for accessibility purposes it is best to add `role="list"` to `ul` and `ol` elements that have `list-style: none`.

https://unfetteredthoughts.net/2017/09/26/voiceover-and-list-style-type-none/
https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html

I'm not sure if this would be possible because the rule wouldn't know about styles that were not inline with the element, but would it be possible to add some sort of bypass to the rule in such cases?

**Comment by jessebeach** [comment]
Yes, this seems reasonable. Theory and praxis collide!

**Comment by jessebeach** [comment]
@mikeriley131 you can do this today. I added a test case in #707 

<img width="643" alt="Screen Shot 2020-06-20 at 3 25 40 PM" src="https://user-images.githubusercontent.com/345913/85212746-a22b1a00-b30a-11ea-810c-9e397010a3a2.png">

**Comment by mikeriley131** [comment]
Wonderful. Thank you.
