### ISSUE TITLE
Additional acceptible case for no-noninteractive-element-interactions?

### ISSUE THREAD

**Issue by angry-dan** [jsx-eslint/eslint-plugin-jsx-a11y#692]
Following recommendations found here - https://inclusive-components.design/cards/ - for creating cards we're hitting 
no-noninteractive-element-interactions and click-events-have-key-events errors. 

I personally think that this code is accessible:

```
<li onClick={event => event.currentTarget.querySelector('a').click()}>
    <a href="http://example.com">Card title here</a>
</li>
```

This is as a pattern for cards. In reality the li will contain other content such as an image and teaser text that we don't want to be part of the link. The click handler in our case doesn't make the li into a button or require any role, it's just there to aid accessibility with mouse and tablet users - to make the click surface area bigger. This might well make the rule unsuitable in which case we're happy to put an ignore above our click handler - but I'd like it clarified in case we're missing something.

**Comment by ljharb** [comment]
I'm a bit confused; if the other content isn't meant to be part of the link, then why would a user expect clicking it to click the link?

**Comment by angry-dan** [comment]
It's a card component - think of having three cards in a row with an image and a title as calls to action for various parts of a site? It's a pretty common ux technique. For example, [The Guardian's](https://www.theguardian.com/uk) homepage has lot's of clickable cards. Notice that you can click even past the heading and in the whitespace surrounding the text. The cards give additional context to the link - it's text that you'd expect to interact with like a link but a screen reader would read as text, not as part of the link itself.

That [other article](https://inclusive-components.design/cards/) I shared above - gives a bit more detail on the different approaches that you can take, and that (over simplified) example that I gave above is in my opinion the best one to take.

**Comment by jessebeach** [comment]
```
<li onClick={event => event.currentTarget.querySelector('a').click()}>
    <a href="http://example.com">Card title here</a>
</li>
```

@angry-dan no, putting a click handler on a listitem confounds its semantics. It's a container, not an interactive element. The `<a href>` is interactive. You can get the same effect by making the `a` element `display:block` and defining the card size you want. That'll make it the large size that you need, with the larger hit area. If the `a` contains interactive content itself, then make the card hit area `a` tag a sibling of the card content holder.

```
 <li>
    <a class="card-click-catcher" href="http://example.com" aria-label="Card label"></a>
    <div class="card-contents"><a href="">Some other link</a></div>
</li>
```
