### ISSUE TITLE
Update published version

### ISSUE THREAD

**Issue by chrisands** [jsx-eslint/eslint-plugin-jsx-a11y#698]
Is it possible to publish a new version of `eslint-plugin-jsx-a11y` with peerDependency `eslint: ^7`?

**Comment by JayCanuck** [comment]
Same situation here, would love a published update with compatible peerDependency for eslint 7.x.

**Comment by jessebeach** [comment]
@chrisands & @JayCanuck, my friends, we do provide. Check out version 6.3.x

<img width="336" alt="Screen Shot 2020-06-20 at 2 53 26 PM" src="https://user-images.githubusercontent.com/345913/85212255-e5cf5500-b305-11ea-9256-8b527632adfc.png">
