### ISSUE TITLE
New rule: forbid the native dialog element?

### ISSUE THREAD

**Issue by danielnixon** [jsx-eslint/eslint-plugin-jsx-a11y#700]
Motivation: https://www.scottohara.me/blog/2019/03/05/open-dialog.html

**Comment by jessebeach** [comment]
I appreciate the motivation, but I can't bring myself to agree that this library should have an opinion on elements in this way. Browser implementations will vary. This plugin should help an author create a valid Accessibility Tree shape, according to the ARIA standards.
