### ISSUE TITLE
New rule: forbid input type=number?

### ISSUE THREAD

**Issue by danielnixon** [jsx-eslint/eslint-plugin-jsx-a11y#701]
Motivation: https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

**Comment by jessebeach** [comment]
I appreciate the motivation, but I can't bring myself to agree that this library should have an opinion on elements in this way. Browser implementations will vary. This plugin should help an author create a valid Accessibility Tree shape, according to the ARIA standards.
