### ISSUE TITLE
Contradicting linting issue with jsx-a11y/role-supports-aria-props

### ISSUE THREAD

**Issue by leducquan** [jsx-eslint/eslint-plugin-jsx-a11y#704]
Since the latest update, getting linting issue:

``Elements with the ARIA role "heading" must have the following attributes defined: aria-level  jsx-a11y/role-has-required-aria-props``

After adding the aria-level, getting a contradicting error:

``The attribute aria-level is not supported by the role heading  jsx-a11y/role-supports-aria-props``

**Comment by andeykovayov** [comment]
Have exactly the same issue! 
Thanks @leducquan

**Comment by jessebeach** [comment]
I know exactly why this is happening :/

Fixing it now.

**Comment by jessebeach** [comment]
> jessebeach closed this in A11yance/aria-query#63 11 minutes ago

Github has started auto-closing linked issues?

**Comment by ljharb** [comment]
When the merger has close rights on the linked issue, it's always auto-closed it afaik.
