### ISSUE TITLE
Add context to no-noninteractive-tabindex on when this might be valid

### ISSUE THREAD

**Issue by backwardok** [jsx-eslint/eslint-plugin-jsx-a11y#717]
There's a use case for adding `tabindex="0"` to a generic container (like a `<div>`) to [add keyboard accessibility to a scrollable container](https://dequeuniversity.com/rules/axe/3.5/scrollable-region-focusable). Without the `tabindex` attribute, if the scrollable container doesn't contain any interactive elements, you won't be able to scroll that content with a keyboard. 

Since there's no role associated with this, there isn't really anything to key off of to determine that this shouldn't be checked. The only current workaround for this is to disable the rule for that line.

**Comment by backwardok** [comment]
BTW I thought about adding something to this when I was updating all the docs today, but I wasn't super sure what the recommendation should be.

**Comment by kr8n3r** [comment]
yep, long `code` block wrapped in `pre`.  tabindex` goes on the `pre` element

**Comment by eps1lon** [comment]
PR up over at https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/760.
