### ISSUE TITLE
why name it a11y instead of ally? terminal font `11` looks almost same as `ll` (lowcase L)

### ISSUE THREAD

**Issue by danbirle** [jsx-eslint/eslint-plugin-jsx-a11y#731]
@@@@@@@@

**Comment by ljharb** [comment]
@danbirle because `a11y` is short for "accessibility", ie, a + 11 letters + y. `l10n` is short for "localization", similarly.

**Comment by danbirle** [comment]
@ljharb oh, makes sense! thanks for explaining
