### ISSUE TITLE
Missing lang attribute not caught

### ISSUE THREAD

**Issue by anuvenkatesh1** [jsx-eslint/eslint-plugin-jsx-a11y#738]
Hi 

  I'm using CRA to build my React app which came pre-packaged with eslint-plugin-jsx-a11y. I do not have any specific style guide such as airbnb configured either because CRA and airbnb seemed to refer different versions of eslint which resulted in conflict errors. I have tested out a couple of rules of eslint-plugin-jsx-a11y such as alt-text and anchor-is-valid and hence I know that the plugin is working. However, I found that a few rules aren't working as expected. In the snippet below you can see that the <html> tag is missing "lang" attribute. However, the plugin failed to catch it
![missing_lang_attr](https://user-images.githubusercontent.com/32471459/91760557-6a511600-eb88-11ea-8e35-e4787e27b10f.jpg)

Kindly advise on how to remediate this or if this is a genuine miss from the plugin's side?

FYI. I'm also using react-axe version 3.5.3 in addition to this plugin. Hope this isn't conflicting with this plugin's ability to catch some of the issues.

**Comment by evcohen** [comment]
Hi! I think this looks like the `index.html` file that CRA creates by default. This plugin only works on JSX syntax (specifically, `.js(x)` files), so it won't enforce anything within that file. If you prefer, you can manage the document head using something like `react-helmet` (https://github.com/nfl/react-helmet). Thank u!!
