### ISSUE TITLE
label-has-associated-control failing to catch explicit labelling that's missing htmlFor and id attributes

### ISSUE THREAD

**Issue by anuvenkatesh1** [jsx-eslint/eslint-plugin-jsx-a11y#739]
Hi

  I'm using CRA to build my react app and it came prepackaged with this plugin. I don't have any special eslint style guide configured such as airbnb. I'm also using react-axe 3.5.3 in tandem to catch additional A11y issues not covered by this plugin.

Issue:
I have the following code in one of my components.
![label_for_id](https://user-images.githubusercontent.com/32471459/91763505-88b81100-eb8a-11ea-8af4-eb2d6506aabc.jpg)

As seen above, I'm doing explicit labelling and the htmlFor and id attributes are missing to tie the label tag to its input control. The plugin is failing to catch this issue. Kindly advise if something is missing in my implementation or if its a genuine miss from the plugin's side. Thank you

**Comment by ljharb** [comment]
CRA has very few useful eslint rules turned on, and most of the ones that are on are only warnings. You'll likely have to enable additional rules yourself to catch things like this.

**Comment by anuvenkatesh1** [comment]
@ljharb 
Thank you. I'm a beginner in React, CRA etc. Forgive me if this is a naive question. I added the following
"plugins": [
      "jsx-a11y"
    ],
      "extends": [
        "plugin:jsx-a11y/strict"
      ]

to my package.json to "include" and recommended rules of the plugin but that didn't help. CRA doesn't honor this is it as it comes pre-packaged with this plugin and set to include only some basic rules?

**Comment by ljharb** [comment]
I don't use CRA myself, but I think you need to eject to be able to do most anything useful in CRA, including modifying the eslint configuration.

**Comment by anuvenkatesh1** [comment]
Update: I created a .eslintrc file and added the following to it. Earlier I had added it to package.json by mistake. It should go in the .eslintrc file and that seems to overcome the limitations with the CRA's default eslint capabilities. 
"plugins": [
"jsx-a11y"
],
"extends": [
"plugin:jsx-a11y/recommended"
]

Thanks for the help. Will close the ticket.
