### ISSUE TITLE
fieldset should allow role="radiogroup"

### ISSUE THREAD

**Issue by wjmao88** [jsx-eslint/eslint-plugin-jsx-a11y#743]
I've encountered an error trying to put `radiogroup` as a role on a `fieldset`
![image](https://user-images.githubusercontent.com/5618503/93527683-3bb49880-f907-11ea-820d-6b4b10edc637.png)

but according to MDN, radiogroup is a permitted role on `fieldset` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

![image](https://user-images.githubusercontent.com/5618503/93527748-525aef80-f907-11ea-8167-e8f68e956e74.png)

**Comment by hallzac2** [comment]
I created https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/746 to address this 😄
