### ISSUE TITLE
`no-static-element-interactions` message suggests adding a role, but not changing the element.

### ISSUE THREAD

**Issue by threehams** [jsx-eslint/eslint-plugin-jsx-a11y#761]
(sorry about the title, this is a very tough title to write)

The [docs for the no-static-element-interactions rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md) cover two common cases of needing a static element.

The message on error:
```
Static HTML elements with event handlers require a role.
```

This typically happens in pairs with `click-events-have-key-events`:
```
Static HTML elements with event handlers require a role. (jsx-a11y/no-static-element-interactions)
Visible, non-interactive elements with click handlers must have at least one keyboard listener. (jsx-a11y/click-events-have-key-events)
```

However, both the docs and message are dancing around an issue: _people use clickable divs because they don't know any better_. Making an interactive `div` accessible requires a minimum of 3 extra properties, plus all the keyboard event handlers on top of click handlers (and all the `keyCode` listening necessary to match the role). The best fix for this rule is almost always to change the static element into an interactive element, but the message sends people down a more difficult and verbose path.

Would you be willing to accept a change to have the message reflect this? I'm struggling with grammar consistency, but something like:
```
A static HTML element with an event handler requires a role, or should be replaced with an interactive element.
```

**Comment by ljharb** [comment]
That makes sense to me. @jessebeach?

**Comment by jessebeach** [comment]
I agree with @threehams that the best solution is a semantic element. So I suggest leading with that, rather than pushing the optimal recommendation to the end of the sentence after an or clause. Something like:

```
The best replacement for an interactive static element is the corresponding semantic HTML element. In the case that this replacement is not possible, then an interactive static element requires a role and tabbing support as well as interaction support for mouse, keyboard and touch inputs.
```

**Comment by SalahAdDin** [comment]
It is even not clear for me which are the static elements.
