### ISSUE TITLE
How make ESLint support for the experimental syntax 'jsx' if it isn't currently enabled?

### ISSUE THREAD

**Issue by DimaIpatii** [jsx-eslint/eslint-plugin-jsx-a11y#765]
I'm trying to setup workflow to my React app, using Webpack 5 + Babel 7 + Eslint 7.
As parser I'm using "@babel/eslint-parser" , and in my index.js when I render a React component the ESLInt says that "Support for the experimental syntax 'jsx' isn't currently enabled".
I tried to use the "eslint-plugin-jsx-a11y", and other methods but it doesn't help...
It is my first project when I'm using ESLint, I started to read its huge documentation, different articles about how to set it, and seams that I do it well, but the result is not.

Here's the Repo:
[https://github.com/DimaIpatii/react-quotes-machine](url)

### Error in index.js and App.js:

<img width="1261" alt="Screenshot 2021-01-12 at 11 02 52" src="https://user-images.githubusercontent.com/32913446/104327262-db1b1e00-54ea-11eb-8710-c9dee46da7eb.png">

**Comment by ljharb** [comment]
For the default eslint parser, set `parserOptions: { ecmaFeatures: { jsx: true } }`. For babel-eslint, you have to set up your babel config to parse jsx (which i think it does by default).

Closing, since it’s not related to this plugin.
