### ISSUE TITLE
`no-static-element-interactions` cannot be resolved with dynamically-defined roles

### ISSUE THREAD

**Issue by bcronin2** [jsx-eslint/eslint-plugin-jsx-a11y#766]
I'm not sure if this behavior is intentional, but in order to satisfy the `no-static-element-interactions` check, a single string literal must be provided for the role:

![image](https://user-images.githubusercontent.com/6960884/105061409-540bff80-5a2e-11eb-9104-c0b676af1665.png)

There are workarounds to this, but it'd be nice if it were possible to specify that the role be one of two (or more) dynamically determined interactive roles (as in the example).

**Comment by ljharb** [comment]
Linters can not analyze dynamic values at all.

**Comment by bcronin2** [comment]
Fair enough, good to know

**Comment by ljharb** [comment]
Although, in this specific case (a ternary with literals on both sides) the rule should be able to handle it. PRs welcome.

**Comment by V2dha** [comment]
Can I work on this?

**Comment by ljharb** [comment]
Go for it! Anything with "help wanted" is up for grabs.

**Comment by V2dha** [comment]
@ljharb for getting the prop value assigned to the `role` attribute, I am using `getProp` and `getPropValue` functions 
`const roleProp = getPropValue(getProp(attributes, 'role'));` 
but while getting its type it is giving me error. `roleProp.type === 'ConditionalExpression'` 
Does the function just returns the value and not the node?
