### ISSUE TITLE
React eslint error

### ISSUE THREAD

**Issue by spandey1296** [jsx-eslint/eslint-plugin-jsx-a11y#767]
src\components\Tracks.js
  Line 54:16:  Redundant alt attribute. Screen-readers already announce `img` tags as an image. You don’t need to use the words `image`, `photo,` or `picture` (or any specified custom words) in the alt prop  jsx-a11y/img-redundant-alt

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

All tags are correct but it is showing error

**Comment by ljharb** [comment]
What’s the code being warned? Note than an alt of “image” is an error.

**Comment by Felicia5** [comment]
I think you get this message when you add "image" as your alt text in the img HTML tag like this:  < img alt = "image" >Screen readers recognise the img as an image tag, so adding "image" as a description is redundant.

**Comment by ljharb** [comment]
Closing for now, pending reproduction code.
