### ISSUE TITLE
Will Plugin work in Package.json eslintConfig?

### ISSUE THREAD

**Issue by jrock2004** [jsx-eslint/eslint-plugin-jsx-a11y#776]
Should I be able to add the following section to my package.json and it should work? Or is it required I have a .eslintrc?

```
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest",
      "plugin:jsx-a11y/strict"
    ]
  },
```

**Comment by ljharb** [comment]
You also need `"plugins": ["jsx-a11y"]`, i believe, but yes, "eslintConfig" and `.eslintrc` are the same.

However, note that increasing the size of package.json makes your package slower to install, and mixes up the git diffs on the eslint config with those with the rest of package.json.

**Comment by jrock2004** [comment]
Thank you, this worked
