### ISSUE TITLE
Deprecated rule no-onchange is still enforced

### ISSUE THREAD

**Issue by snood1205** [jsx-eslint/eslint-plugin-jsx-a11y#790]
Despite the rule `no-onchange` being deprecated in the [documentation](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-onchange.md), the rule itself is still being enforced. Using eslint-plugin-jsx-a11y version 6.4.1 with the following code
```tsx
<select value={configuration} onChange={handleConfigurationChange}>
  <option value="conference">Conference</option>
  ...
</select>
```
I get the error
```
error  onBlur must be used instead of onchange, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users  jsx-a11y/no-onchange
```

**Comment by ljharb** [comment]
What do you mean "still being enforced"? Are you referring to the recommended config?

**Comment by ljharb** [comment]
#757 is what marked it as deprecated, and also removed it from those configs; it's just not released yet.

The docs for the latest released version are https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/v6.4.1/docs/rules/no-onchange.md
