### ISSUE TITLE
Webpack 5 and buggy @babel/runtime version

### ISSUE THREAD

**Issue by maxcnunes** [jsx-eslint/eslint-plugin-jsx-a11y#795]
Hey there 👋 Looks like the latest version of this module `v6.4.1` is pinned to a buggy version of `@babel/runtime`  [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/v6.4.1/package.json#L61), and this is the ticket describing that issue https://github.com/babel/babel/issues/8462. I just noticed this issue once I migrated my project to Webpack 5, so it may have some related, but the root cause is really that buggy version of babel runtime. I know this project has nothing to do with Webpack, but because of NPM dedupe logic, it seems the version of babel runtime defined by this project is deduped and reused by all the other modules. Just for reference, here there are some more details about this issue https://github.com/sqlectron/sqlectron-gui/issues/659.

I noticed that the master branch is already pinned with a new version of that dependency. Any chance we get a new release out, the last one was 7 months ago.

Thanks for this great project btw!

**Comment by ljharb** [comment]
It's not pinned at all; it's using `^`, so the latest version works just fine.

You can reinstall this package and it'll use the latest version of transitive deps. No new release here is required.

**Comment by maxcnunes** [comment]
Ah right, pinned wasn't the right term for that. Reinstalling the package didn't solve the issue in my case though, NPM kept using that old version for all dedupe logic. 

Installing and uninstalling `@babel/runtime` latest version as a direct dependency forced the package-lock.json to upgrade the version used for dedupe which fixed this issue in my case.
