### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by danantal** [jsx-eslint/eslint-plugin-jsx-a11y#797]
Hi

Thanks for this awesome plugin!

I was wondering if a new version is up for being released soon? Apparently this [feature](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/720) fixed in this [PR](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/749) has been merged last year in December, but it still has not been released.

The documentation also [states that it should work with Glob support](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/749), so I was bugging my head a bit what I was doing wrong until I realized it was never released 😅 .

Also the last release listed here is from 2019: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/releases, while the latest tag is for 6.4.1 which was released in 2020.

Could you facilitate a new release?

**Comment by danantal** [comment]
@evcohen @jessebeach Since you released the latest versions officially - maybe you can help here? 👼

**Comment by ljharb** [comment]
Certainly you always need to look at the docs that match the version you're using :-)

We'll do a release at some point soon.

**Comment by danantal** [comment]
I am not sure how to browse documentation per release to be honest - other than looking through commit hashes which is not optimal... Anyway - my point is that a lot of people expect features to work as advertised in the documentation - especially when you are on the latest.

**Comment by papuruth** [comment]
Please update jsx-ast-utils to fix this The prop value with an expression type of JSXFragment could not be resolved. Please file issue to get this fixed immediately.

**Comment by ljharb** [comment]
@papuruth there are no unreleased fixes in jsx-ast-utils.

@danantal go to the branch dropdown and select the matching tag - eg, https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/v6.4.1/docs/rules

**Comment by Svish** [comment]
Also looking for a release, so the deprecated `no-onchange` is removed from the recommended ruleset (as it is in current code, but not in latest release on npm)

**Comment by danantal** [comment]
Hey guys

Sorry for pushing - I don't mean to be annoying but it's been almost a year since your last release and there are quite a few people waiting for the different fixes implemented since - hence the upvotes for the feature.

Can I help in any way to facilitate a new release?

**Comment by ljharb** [comment]
v6.6.0 is released (v6.5.1 was released in November 2021, so this should have been closed then).
