### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [jsx-eslint/eslint-plugin-jsx-a11y#809]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by ljharb** [comment]
It'd be great to tee up a PR, but we won't officially support anything until v8 is actually released (betas don't count any more than rc's do).
