### ISSUE TITLE
1:24:30 PM:   Line 13:9:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

### ISSUE THREAD

**Issue by ElhadiRagabaat** [jsx-eslint/eslint-plugin-jsx-a11y#813]
1:24:30 PM:   Line 13:9:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

**Comment by ljharb** [comment]
Without the code being warned on, and without any actual explanation of why you're filing the issue, it seems like the warning text should be clear enough instructions.
