### ISSUE TITLE
[Docs] removal of react-a11y mention in documentation

### ISSUE THREAD

**Issue by uidev547** [jsx-eslint/eslint-plugin-jsx-a11y#829]
In **Why** section in README.md it is mentioned about **react-a11y** project. Can we remove **react-a11y** mentioning as it is **deprecated**.

*Note: This project does not replace react-a11y, but can and **should** be used in conjunction with it* 
Above statement is README.md sounds like  **react-a11y** is mandatory to use along with  **eslint-plugin-jsx-a11y**, Though there is no dependency on **react-a11y**.

**Comment by ljharb** [comment]
Indeed, given that that project hasn't been updated in 3 years (altho it is not deprecated), it should be removed from the docs.

**Comment by uidev547** [comment]
@ljharb Thank you for response.
yeah may be it is not deprecated, but it has deprecation notice. looks like a red flag.

**Comment by ljharb** [comment]
I see that on the repo, but it's not deprecated on npm. I filed https://github.com/reactjs/react-a11y/issues/183 to fix that.
