### ISSUE TITLE
DL should not have implicit list role 

### ISSUE THREAD

**Issue by tahme** [jsx-eslint/eslint-plugin-jsx-a11y#847]
Only `ol` and `ul` should have an implicit list role, not `dl`. https://www.w3.org/TR/wai-aria-1.1/#list

(In ARIA 1.3 draft there's an `associationlist` role for `dl` https://w3c.github.io/aria/#associationlist)

**Comment by ljharb** [comment]
Which rule is this? Do you have some example code that you think should, or shouldn't warn?

**Comment by tahme** [comment]
In my tests I wanted to select a `dl` by role. I found out that according to the specs `dl` has no implicit role so I tried `<dl role="list">`, which gave me a `jsx-a11y/no-redundant-roles` error, which shouldn't happen. I assume the relevant code for `dl` is https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/util/implicitRoles/dl.js 

(In the end I decided against using the `list` role for `dl`.)

**Comment by ljharb** [comment]
Interesting, it seems like indeed a `dl` currently has no implicit role (altho it may have `associationlist` later). Thanks!
