### ISSUE TITLE
Custom components release

### ISSUE THREAD

**Issue by lishine** [jsx-eslint/eslint-plugin-jsx-a11y#852]
Is it disabled now in main?
I saw a PR merged, but could not make it work even from

```
		"eslint-plugin-jsx-a11y": "https://github.com/jsx-eslint/eslint-plugin-jsx-a11y.git"
```

How do I enable it?
When will you release it ?

Thank you!

**Comment by ljharb** [comment]
Duplicate of #851.

Don't consume from github; only from npm.

The feature isn't released yet, and there's no concrete timeline for it - you'll have to be patient.
