### ISSUE TITLE
Add support for aria-description

### ISSUE THREAD

**Issue by gabibianconi** [jsx-eslint/eslint-plugin-jsx-a11y#853]
aria-description is not supported in version 6.5.1

![aaaaaaaaaaaaa](https://user-images.githubusercontent.com/25694348/170113104-dad0d6cc-5e46-446b-b655-ddc100d9de75.png)

**Comment by eliw00d** [comment]
I'm guessing that technically this library should support `aria-description` whenever its npm dependency `aria-query` also supports it: https://github.com/A11yance/aria-query/issues/57#issuecomment-643981132

This is based on https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/rules/aria-props.js#L10 and https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/rules/aria-props.js#L15.

**Comment by nico3333fr** [comment]
Same issue there in Proton, I need to use it as suggested here when asking https://github.com/w3c/aria/issues/1869 but the linter says no, even if I hear it working nicely with VoiceOver. 

Is it something easy to add?

**Comment by ggurbina** [comment]
Having the same issue here

**Comment by ljharb** [comment]
We’ll be able to do that as soon as i cut the next release of aria-query.

**Comment by ljharb** [comment]
e51793729e5e366e30d2f3bf0f253f2bdb9e6523 has unpinned the dep, so I'm going to close this.

In theory, the next release should fix it.
