### ISSUE TITLE
Add command to initialize .eslintrc config file in readme

### ISSUE THREAD

**Issue by V2dha** [jsx-eslint/eslint-plugin-jsx-a11y#859]
Following the steps in the readme, while using the plugin, it would be helpful for beginners like me on eslint if the command on initializing the `.eslintrc` config file is added to set up the plugin i.e. `npm init @eslint/config` in the usage section of the readme.

**Comment by ljharb** [comment]
The command for that is `eslint init`, and it's in the eslint documentation itself. I don't think individual plugins should be documenting things that eslint documents, but we could perhaps link to the relevant place in eslint's docs?

**Comment by V2dha** [comment]
Perhaps in the readme instead of linking to [ESLint](https://eslint.org/ ), we can redirect it to [Getting started with ESLint]( https://eslint.org/docs/latest/user-guide/getting-started)

**Comment by ljharb** [comment]
That sounds great.
