### ISSUE TITLE
Possible exception for anchor-is-valid rule

### ISSUE THREAD

**Issue by claireryberg** [jsx-eslint/eslint-plugin-jsx-a11y#864]
The following code is being used as a link that navigates back to the previous page, but it fails the `anchor-is-valid` rule.

```
<a href="javascript:window.history.go(-1)">
```

Is there a better value that could be used for the `href`, or would this be considered an exception to the rule? Since this is being used for page navigation, I don't think a `button` is a better option. 

This is the error:
```
The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. 
If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles.
```

**Comment by ljharb** [comment]
Such a link is a bad practice, because it duplicates the back button that’s already in every single browser.

**Comment by claireryberg** [comment]
Can you elaborate on why it's bad practice? Offering the same behavior in more than one location doesn't block the user experience in anyway, and depending on the design could make sense.

**Comment by fregante** [comment]
I see several problems with it:

- it's does not _navigate to_ a page, it _navigates back_. I can't open it in a new tab, I can't add it to my favorites, I can't download it, I can't share it, … you get the gist. That's not a link, it's a `button`.
- it's effectively an inline script, which is bad practice. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script for context
- if you're building an interactive/react component, you should probably use a native way to "go back to the previous route"
- as mentioned, it duplicates native behavior, which is only ok if you're building a UI-less PWA or similar webview

The error is super clear:

- `Provide a valid, navigable address as the href value.`

`javascript:*` is not a navigable address, it's a hack from 1995, don't use it.

**Comment by ljharb** [comment]
Thanks, that's a much more thorough answer.
