### ISSUE TITLE
document allowExpressionValues option

### ISSUE THREAD

**Issue by ljharb** [jsx-eslint/eslint-plugin-jsx-a11y#867]
~Three~ Two rules use this option, and none of them document it.

We should also audit the test cases for these rules and ensure that they all behave appropriately when this option is set to true, set to false, and omitted (ie, defaults to false).

**Comment by V2dha** [comment]
Apart from `no-static-element-interactions` and `no-noninteractive-tabindex`, which is the third rule that uses this option? 
I'll add documentation for these rules and test cases for them similar to in `no-static-element-interactions`.

**Comment by V2dha** [comment]
Also, @ljharb in `no-noninteractive-tabindex` rule, would it make sense to add the specific case for role assignment using ternary on literals both sides similar to `no-static-element-interactions` rule in order to add the test cases for them with `allowExpressionValues` set to true?
