### ISSUE TITLE
Help needed on how I can set up dev environment

### ISSUE THREAD

**Issue by 1snow2** [jsx-eslint/eslint-plugin-jsx-a11y#868]
Hi, I am new to Github and Eslint, recently start playing around this plugin, got some questions about environment setup. 
What I did so far: 1) clone the Eslint repo to my laptop 2) installed the plugin with command 'yarn add eslint-plugin-jsx-a11y --dev'
 3) config the plugin in file .eslintrc 
4) From Eslint docs, https://eslint.org/docs/latest/developer-guide/unit-tests I could run the test successfully with command 'npm run test:cli /lib/rules/no-undef.js' and 'npm test'

My noob questions:
1. I have followed instruction to config the plugin https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#installation, how could I run a rule from this plugin? For example, I want to run aria-props rule or we could only run aria-props-test? 
2. Should I run under eslint-plugin-jsx-a11y folder? 
3. which command is the right one I could use? 

Thanks for help!

**Comment by ljharb** [comment]
I'm a bit confused. You don't need to clone the eslint repo anywhere unless you're trying to make changes to eslint itself.

If that is what you're trying to do, then you'd need to file an issue on eslint itself with questions.

To make changes to this plugin, you'd clone this plugin's repo (and not eslint's).

**Comment by 1snow2** [comment]
@ljharb  Thanks for your reply! I think I am a little more clear now. come up with more questions. 
1. So once I clone the plugin repo,  If I want to run some Accessibility rules, for example aria-prop rule, what is the right way to run? Should I run aria-prop-test file within this plugin repository? 
2. What happens if I plan to contribute to introduce some new rules to this plugin? Jesse suggested me to start with test cases and work backwards since Test coverage is very important. I am wondering what is the right process from my project start to end to develop a new rule?  Like from define the rules, implement test, then develop the rule, after that should have some verification processes. 

Thanks again for answering my noob questions!

**Comment by 1snow2** [comment]
@ljharb Thanks for these brilliant answers! I already started looking into some wanted rules from this list https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues?q=is%3Aissue+is%3Aopen+label%3A%22new-rule%22+. I do think 'If you want to run this project's tests for one of this project's rules, you'd clone the project, npm install, and npx jest path/to/test/file, or npm run tests-only to run them all.' solve my questions.

**Comment by 1snow2** [comment]
@ljharb  I will close!
