### ISSUE TITLE
jsx-a11y/control-has-associated-label off in both recommended and strict

### ISSUE THREAD

**Issue by jmhouzz** [jsx-eslint/eslint-plugin-jsx-a11y#874]
Hi, in the _Rule strictness in different modes_ section of readme, the `control-has-associated-label` is listed as `error` for both recommended and strict mode. But it's actually turned off in both of those configs.

It seems like that's always been the case? 
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/commit/56506740f826433bd498be14a7ec1aff94753ace#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R62

What's up with that? Is it off due to performance or by a mistake?

<img width="629" alt="image" src="https://user-images.githubusercontent.com/48897197/178642789-fad1bf8c-bacf-4974-9fbc-87542d805668.png">

**Comment by ljharb** [comment]
You're right; the autogenerated list says everything is an error, and doesn't actually check the configs.

**Comment by jmhouzz** [comment]
Thank you so much for the clarification and the fix @ljharb!
