### ISSUE TITLE
Bump aria-query to v5 to reduce install size

### ISSUE THREAD

**Issue by ArnaudBarre** [jsx-eslint/eslint-plugin-jsx-a11y#889]
The version 4 depends on @babel/runtime-corejs3 which depends on core-js-pure, a non negligible 12M dependency.

Changelog: https://github.com/A11yance/aria-query/blob/main/CHANGELOG.md#500

Package Phobia: https://packagephobia.com/result?p=aria-query@5.0.2 (which is less than what I effectively get locally)

Edit: Sorry, I didn't check open pull requests. Fix: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/814

**Comment by ljharb** [comment]
This is an eslint plugin; its size is utterly irrelevant. Install size is a non-problem - only bundle size matters (and bundle size can’t be measured without the entirety of your application available).
