### ISSUE TITLE
[Question] Is this eslint plugin only for React or will it work on any JSX code?

### ISSUE THREAD

**Issue by 100terres** [jsx-eslint/eslint-plugin-jsx-a11y#899]
Is this eslint plugin only for React or will it work on any JSX code? Like [solid](https://github.com/solidjs/solid)?

**Comment by ljharb** [comment]
It should theoretically work on any jsx code, but all the rules have been written with React in mind (just like jsx itself was). You'd have to try it and see.

**Comment by 100terres** [comment]
@ljharb perfect. Thank you!
