### ISSUE TITLE
Repo tooling: add testing to ensure each rule has a corresponding .md

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [jsx-eslint/eslint-plugin-jsx-a11y#903]
Following the thread from https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/833#issuecomment-1292935945: it'd be great to have testing make sure each rule is documented. In typescript-eslint we make sure rule docs exist at a certain path and follow a certain format ([typescript-eslint > `docs.test.ts`](https://github.com/typescript-eslint/typescript-eslint/blob/344322add846d03c6c9981e486b09e6ba1196555/packages/eslint-plugin/tests/docs.test.ts)).

I'm up for contributing this if you'd like it!

**Comment by ljharb** [comment]
I agree, and yes that’d be great - although it’s possible that #901 might provide this already. @bmish?

**Comment by bmish** [comment]
Yes, since [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) checks all rule docs, it will already fail when a rule doc is missing.

**Comment by JoshuaKGoldberg** [comment]
Nice, love it!
