### ISSUE TITLE
Quick question, does this library can work in Angular webapps?

### ISSUE THREAD

**Issue by dani-oropeza-nic** [jsx-eslint/eslint-plugin-jsx-a11y#908]
I would like to know if this library can work in Angular web applications. I saw in the description that is says that is for React apps. But it does not says explicit that It does not work for Angular. 

If naturally it does not work for Angular webapps, is there a way to integrate this anyway and use the same rules to a certain extend? I was investigatin the other days about technologies for accessibility eslint rules for Angular, but I haven't seen good libraries.

**Comment by ljharb** [comment]
I suppose it could if it uses jsx, which i didn’t think angular does, but it’s definitely only intended for react. You’d have to try it and see, but it’s unlikely we’d make any changes for angular compatibility.

**Comment by ljharb** [comment]
No, none. My understanding is that angular doesn’t use jsx at all, so I’d be surprised if anyone had attempted it.
