### ISSUE TITLE
CI is failing on old Node versions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [jsx-eslint/eslint-plugin-jsx-a11y#914]
Node versions 11 and below are failing in GitHub Actions. They're also past EOL. Can they be removed?

Example: #913 -> https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/actions/runs/3875057562/jobs/6607126082.

**Comment by ljharb** [comment]
The solution is to fix it, not drop them - EOL status is irrelevant, always.

**Comment by ljharb** [comment]
This is due to https://github.com/mattcg/language-tags/issues/15#issuecomment-1376114476; I'll update your PR to pin it.

**Comment by JoshuaKGoldberg** [comment]
Also from https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/915#pullrequestreview-1240993265:

> there's no reason to do it

* There's more CI noise from old versions
* We can't use APIs specific to newer language features
* Syntax has to be transpiled down to older versions, which makes files bigger

Is there another place this has been discussed? And/or other discussions I should look at? To my knowledge, this is the only ESLint plugin that tests so aggressively into old versions - and I don't see any reason to add support for years-out-of-usage Node versions.

**Comment by ljharb** [comment]
eslint-plugin-react and eslint-plugin-import both do it - eslint-plugin-import tests down to eslint v2.

CI noise isn't an actual problem, and newer APIs can be used as long as there's reasonable fallback behavior.

Transpiler output size is irrelevant because this is a dev tool, and disk space is infinite and free.

**Comment by JoshuaKGoldberg** [comment]
> eslint-plugin-react and eslint-plugin-import both do it - eslint-plugin-import tests down to eslint v2.

I should have asked: places you personally have not significant involvement? I don't mean this as a personal jab - just trying to see if there's real demand in the community for old support.

Another point against old version support being useful is that most libraries don't actively test for deprecated Node support. Even if ESLint and all its plugins happen to work, other dev tooling is very likely to not. So, even if eslint-plugin-*s are the only ones supporting old versions, that doesn't mean folks can practically use them.

> CI noise isn't an actual problem

It is for me! It's inconvenient having so many to scroll through. And anecodtally speaking, if there's any duplication in CI runs (e.g. having a dozen Node versions instead of 3-4), it's especially confusing for newer developers.

> disk space is infinite and free

Heh, this isn't going to be my most convincing argument set, but I don't quite agree:

* CI cache times & install sizes are proportional to tool size. The impact of a few ESLint plugins may be negligible, but en masse, it can make an impact.
* Same with installing locally and the disk size people take up - especially for projects like this that still use npm, rather than system-symlinked packages (e.g. with pnpm)
* Getting these plugins into a browser playground is an eventual goal of mine & should be for the ecosystem, I think. It'll be a worse loading experience to load larger size JS.

The way I see it, this project is going _out of its way_ to support old Node versions. If it does an eventual next major version, I don't see any strong justification to _keep_ those old versions.

**Comment by ljharb** [comment]
I agree that there are few major packages at this point that follow my stance, but that doesn't make it wrong :-)

Development isn't significantly harder by using polyfills or fallbacks, and I'm always happy to add them into someone's PR if it's an issue.

I see what you mean about the multiple CI jobs, but usually i just "find in page" on the PR page for "failing", which jumps me directly to the one i need to look at.

A breaking change is going out of one's way, and it forces things like needing to backport security fixes to support downstream usage. The highest cost - including out of everything you've mentioned - to the developer community that I've seen over my entire career comes from package developers who have aggressively dropped node versions, thus incrementing the major, and thus creating ecosystem fragmentation.

Pick a major package that does frequent majors, and look at the download counts for it - how many people get left behind on old majors? Within a single major, virtually everyone is always concentrated on the latest release for it, which is great for security and reliability - but with multiple depended-upon major lines, a bunch of human beings get left out in the cold. It's simply user-hostile to do unnecessary breaking chang

**Comment by ljharb** [comment]
I very much disagree that it is the job of package authors to pressure folks to upgrade node, and I also disagree that it's good - it's actually quite bad. Precisely zero people are stuck on an old node version merely out of laziness, they're stuck there for other reasons that package authors can't change - by making life harder for them, we're making them LESS secure, and we aren't helping them upgrade, we're actually making it much harder.

The standard is, and will be, "we support the same things as close to forever as possible, and we'll only to a semver-major when strictly necessary, and only then will we re-evaluate what's worth supporting".

**Comment by JoshuaKGoldberg** [comment]
That's a good point. Retracted on that front 🙂

**Comment by ljharb** [comment]
Don't get me wrong - if at some point in the future, any of these 3 eslint plugins has a semver-major, it will give me great joy to delete all of the workarounds and branches and test cases for the things being dropped (like the old TS eslint parser, the old babel parser, or older versions of eslint), and my life will be MUCH easier as a result.

However, my personal convenience is eternally less important and less of a priority than the convenience of every single individual user of my software, and I refuse to neglect that burden.

**Comment by JoshuaKGoldberg** [comment]
Very noble 😄 and I can definitely see where you're coming from.

Other than the _"job of package authors to pressure folks to upgrade node"_ point, I still stand by my request, understanding your counterpoints. I'm requesting we put more weight of the personal convenience -or, as I'd put it, time efficiency & ability to be more productive- of the maintainer(s). If working on a project is some percent slower & more aggravating for version support a small percentage of users need, is that really worth it for them?

For example, I try to avoid working in repos that combine odd requirements or restrictions such as old Node versions _(along with other quirky decisions in these repos)_, because I know I'm both less efficient & have less tolerance for debugging as a result of those quirks. I know of other folks who do the same.

If this thread is getting long in the tooth and we've just entrenched our positions, I can stop bothering you with this. But it really feels off to me to go through such effort to keep such ancient support knowing it's slowing down project development.

**Comment by ljharb** [comment]
I think that might be the crux - it's not slowing down project development for the primary maintainer. It certainly might be mildly inhibiting contributors, and I can't speak to that, but it doesn't make sense to me to make technical and product decisions based on reducing potential barriers for contribution (not that reducing barriers wouldn't be a good thing, of course!)
