### ISSUE TITLE
`aria-activedescendant-has-tabindex` docs are outdated

### ISSUE THREAD

**Issue by dummdidumm** [jsx-eslint/eslint-plugin-jsx-a11y#924]
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-activedescendant-has-tabindex.md says that a negative tabindex makes this rule fail. But that was updated in #708, but the docs generator likely wasn't run again for those docs.

**Comment by ljharb** [comment]
The docs generator doesn't handle most of the prose :-) a PR to fix the examples would be appreciated.
