### ISSUE TITLE
Should `mouse-events-have-key-events` check for onMouseEnter/Leave, onPointerOver/Enter/Leave/Out?

### ISSUE THREAD

**Issue by willwull** [jsx-eslint/eslint-plugin-jsx-a11y#927]
As the title says, I'm wondering if the rule `mouse-events-have-key-events.js` should, in addition to only `onMouseOver` and `onMouseOut`, also check for the `onMouseEnter/Leave` and `onPointerOver/Enter/Leave/Out` events?

Some context for this question is that I want to enable `mouse-events-have-key-events` in our codebase, but it turns out we have a separate custom rule that tells you to use `onMouseEnter` instead of `onMouseOver` and `onMouseLeave` instead of `onMouseOut`, so `mouse-events-have-key-events` would effectively not do anything for us I guess...

What do we think? I'm happy to submit a PR, but wanted to ask first in case there are reasons for not supporting those additional events.

Thanks!

**Comment by ljharb** [comment]
that seems reasonable to me - @jessebeach?

**Comment by jessebeach** [comment]
These options should be turned into configuration. I think we just never got around to making this rule configurable. @willwull would you like to propose a PR to make this rule configurable? https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/rules/mouse-events-have-key-events.js

**Comment by willwull** [comment]
@jessebeach sure thing, let me take a stab at this. I'll try to have something within a week
