### ISSUE TITLE
should interactive-role-supports-focus skip role=option?

### ISSUE THREAD

**Issue by ckundo** [jsx-eslint/eslint-plugin-jsx-a11y#935]
We have a `role=listbox` with `role=option` children. those `option`s are failing on `interactive-role-supports-focus`. We're getting around this by applying `tabindex=-1`, which I think is actually correct, but wanted to gut check since[ APG does _not_ use tabindex for their listbox example](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/examples/listbox-scrollable/) (I know APG is reference implemenation, but still makes me doubt the `tabindex=-1`... thoughts?

edit: if tabindex=-1 is not correct, consider skipping `option` for the rule?

**Comment by jessebeach** [comment]
@ckundo are you using a roving tabindex pattern?

**Comment by ckundo** [comment]
@jessebeach decided to just fix this instance to use roving tabindex 😅

**Comment by jessebeach** [comment]
🙏
