### ISSUE TITLE
implicitRoles/select.js: implicit role is now "combobox"

### ISSUE THREAD

**Issue by kantoche** [jsx-eslint/eslint-plugin-jsx-a11y#949]
Hi,

With the Aria 1.2 update, the implicit role of select element is now "combobox".

**Comment by kantoche** [comment]
Hi,

With the Aria 1.2 update, the implicit role of select element is now "combobox".

**Comment by lb-** [comment]
PR up with a change to support this, note that it's a bit more nuanced where listbox or combobox can be valid based on the attributes. Because... it would be boring otherwise :D 

https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/1027

https://www.w3.org/TR/html-aria/#el-select
