### ISSUE TITLE
[feature] suggest tabindex 0 or -1 for interactive-supports-focus

### ISSUE THREAD

**Issue by ckundo** [jsx-eslint/eslint-plugin-jsx-a11y#952]
When `interactive-supports-focus` fails, the only reasonable solution is to add a `tabindex` of either `0` or `-1`.

Modify `interactive-supports-focus` to have `hasSuggestions: true` with a `suggest` array with 2 entries for fixing to 0 or -1.

Related to #951

**Comment by lb-** [comment]
PR up with an implementation for this https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/1023
