### ISSUE TITLE
axe-core dependency breaks nodejs14 compliancy

### ISSUE THREAD

**Issue by Jimbo3993** [jsx-eslint/eslint-plugin-jsx-a11y#953]
Hi,

Our project is running under nodeJs 14.17.0, 

Since yesterday evening, the lint phase can't go through and throws error because "Object.hasOwn() is not a function" whenever it's assessing jsx-a11y eslint rules, 

Prefixing axe-core to version ~4.7 in our package.json fixes it, but it would be nice to mention that nodeJs14 is not compatible atm.  

this is the release note from axe-core about the version 4.8, https://github.com/dequelabs/axe-core/releases/tag/v4.8.0

**Comment by ljharb** [comment]
That sounds like a bug in axe-core. Can you file it there? https://npmjs.com/object.hasown is an easy solution.

**Comment by ljharb** [comment]
(related; https://github.com/dequelabs/axe-core/issues/4127)

**Comment by ljharb** [comment]
This fix was merged into axe-core, so presumably it will be in v4.8.2.
