### ISSUE TITLE
[label-has-associated-control] Glob format not supporting labelComponents

### ISSUE THREAD

**Issue by regexyl** [jsx-eslint/eslint-plugin-jsx-a11y#972]
The [docs](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md) mention that:

> [Glob format](https://linuxhint.com/bash_globbing_tutorial/) is also supported for specifying names (e.g., Label* matches LabelComponent but not CustomLabel, ????Label matches LinkLabel but not CustomLabel).

It seems like glob matching only occurs for `controlComponents`, not `labelComponents` in jsx-a11y/label-has-associated-control, though it seems like (and makes sense) to have it applied to both of them.

**Comment by ljharb** [comment]
I can definitely see both readings (that it applies only to control, and that it applies to both. I think that paragraph needs some splitting up for clarity regardless.

If we can enable glob support on label components in a non-breaking way, then I'm happy to add it.

**Comment by lb-** [comment]
A fix for part of the issue is up (the docs being a bit hard to read) https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/1024

**Comment by lb-** [comment]
PR up for the rest of the fix for this, supporting glob matching in `labelComponents` & refining documentation examples. https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/1025
