### ISSUE TITLE
bug: type declaration for eslint flat config

### ISSUE THREAD

**Issue by TheElegantCoding** [jsx-eslint/eslint-plugin-jsx-a11y#983]
the export of the package is type any and dont have support for types
![image](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/assets/70770072/1510985c-8133-4882-a54f-b404803d5745)

**Comment by ljharb** [comment]
This plugin has no types in it - maybe there's a DT package - and we also don't yet suppoer flat config.

See #891.

**Comment by TheElegantCoding** [comment]
i think for eslint flat config it is needed

**Comment by ljharb** [comment]
Types aren't ever needed because they're not part of JavaScript. If you're using TS, you can use DefinitelyTyped.
