### ISSUE TITLE
Is there a way to set all errors as warnings?

### ISSUE THREAD

**Issue by fullyonline** [jsx-eslint/eslint-plugin-jsx-a11y#988]
We are in the middle of a transition from an old design library to a new one. 
Since the old will be gone in the next year, we won't putting ressources to fix the old one. Instead we want to focus on the new one.

I found a discussion about this topic, with the conclution accessibility should be a show stopper (https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/887)

We want to be accessible. We would like to use this plugin to improve the accessibility in our app, but if we have to fix stuff that's obsolete in less than a year, we wont use the plugin.

Thanks for your time.

**Comment by ljharb** [comment]
Use overrides to disable the rules only on the files using the old system. There’s no one-line way to disable things, nor will there be.

Good luck being able to ever fully remove your old design system; very few companies ever manage to achieve that stage of such a migration.
