### ISSUE TITLE
Upgrade `axe-core` for more features (it's pinned right now)

### ISSUE THREAD

**Issue by norgeous** [jsx-eslint/eslint-plugin-jsx-a11y#989]
Would it be possible to unpin `axe-core` dep?

https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/package.json#L82

Currently it is pinned to `=4.7.0` in `eslint-plugin-jsx-a11y`

The latest available is `4.9.1` (at time of writing)

https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md

Personally, I am interested in any version above `4.7.1`, as that adds support for CSS4 colors such as lch, oklch, lab, oklab

Thanks!

**Comment by norgeous** [comment]
related: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/792

**Comment by ljharb** [comment]
The reason we're pinned to v4.7.0 is due to failing tests; see https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/commit/8d8f0169dbaaa28143cf936cba3046c6e53fa134 and https://github.com/dequelabs/axe-core/issues/4127

If indeed v4.9.0 fixed that, then a PR to unpin it would be great!

**Comment by ljharb** [comment]
You'd need to run the tests with node 4 or 6, yes.

**Comment by norgeous** [comment]
After a bit of dicking about with versions of node, npm and eslint

`npm i -g npm@4; npm i -g npm@6; npm -i eslint@3`

I did some local testing:

| node version | npm version | eslint version | axe-core version | test result | note |
|---------------|----------------|---------------|--------------------|------------|------|
| v6.17.1 | v6.14.16 | 3.19.0 | =4.7.0 | ✅66 | same as `main` branch (just checking) |
| v6.17.1 | v6.14.16 | 3.19.0 | =4.7.1 | ❌8 ✅58| my preference |

The 8 failing tests all fail with the same error (coming from `axe-core` imports):

```
TypeError: Object.values is not a function
```

so yeah, there is a problem with `axe-core` higher than the current pinned version when using node v6! 👍

**Comment by ljharb** [comment]
node versions are what matters, not npm versions, but let's look at the tests on the PR :-)

**Comment by ljharb** [comment]
Fixed in #990.
